// Generated by build_data.py. Do not edit directly.
const PORTFOLIO_DATA = {
  "contacto": {
    "datos_personales": {
      "nombre_completo": "Gabriel Sebastian Herrera Tola",
      "titulo_profesional": "Estudiante de último semestre de Ingeniería Electrónica",
      "correo": "herrerotolagabrielsebastian@gmail.com",
      "telefono": "+591 76599253",
      "direccion": "Calle 4 de Mayo, La Paz, Bolivia"
    },
    "enlaces": {
      "linkedin": "https://linkedin.com/in/gsherrera",
      "github": "https://github.com/Sebaasu",
      "web_personal": "",
      "portafolio": ""
    },
    "proyectos_online": [
      {
        "nombre": "EMU-SIC Web",
        "url": "https://github.com/Sebaasu/emu-sic-web",
        "descripcion": "Simulador Educativo del Procesador SIC (Small Instructional Computer)."
      },
      {
        "nombre": "SIC Assembler",
        "url": "https://github.com/Sebaasu/asm-sic",
        "descripcion": "A robust, two-pass assembler for the Simplified Instructional Computer (SIC), optimized for FPGA development (Gowin BRAM and Verilog)."
      },
      {
        "nombre": "Bitstream",
        "url": "https://github.com/Sebaasu/bitstream",
        "descripcion": "Simulador web interactivo diseñado para visualizar y comprender los métodos de codificación de línea y las técnicas de detección y corrección de errores en sistemas de telecomunicaciones."
      },
      {
        "nombre": "VSRG-Piano 8086",
        "url": "https://github.com/Sebaasu/vsrg-piano-8086",
        "descripcion": "Juego de ritmo vertical de 12 teclas escrito íntegramente en ensamblador x86 (16 bits) para MS-DOS/DOSBox con sonido polifónico TDM y controlador de teclado personalizado."
      },
      {
        "nombre": "2nd-Order Simulator 8086",
        "url": "https://github.com/Sebaasu/2nd-order-simulator-8086",
        "descripcion": "Simulador interactivo en tiempo real de sistemas de control de segundo orden escrito en ensamblador x86 (16 bits) para MS-DOS/DOSBox, utilizando el coprocesador matemático FPU 8087/80387 para aritmética de punto flotante de doble precisión y graficación VGA (640x480) con soporte para mouse."
      },
      {
        "nombre": "Simple Paint 8086",
        "url": "https://github.com/Sebaasu/simple-paint-8086",
        "descripcion": "Lienzo de dibujo libre en ensamblador x86 (16 bits) para MS-DOS/DOSBox en modo gráfico VGA, que implementa el algoritmo de línea de Bresenham con operaciones de solo enteros, control de cursor dinámico contra parpadeos y ciclado de paleta de colores."
      }
    ]
  },
  "habilidades": {
    "herramientas_software": [
      "LTSpice",
      "Proteus",
      "Scilab",
      "Octave",
      "MATLAB",
      "Logisim",
      "Quartus",
      "Zinjai",
      "Gowin IDE",
      "Step 7-Micro/WIN (Siemens)",
      "OpenPLC Runtime"
    ],
    "lenguajes_y_hdl": [
      "C++",
      "Java",
      "Python",
      "VHDL",
      "Verilog",
      "Arduino",
      "LaTeX",
      "AHPL",
      "CUPL",
      "Assembler",
      "Ladder/STL",
      "Structured Text (ST)"
    ],
    "plataformas_hardware": [
      "Arduino",
      "ESP32",
      "PIC",
      "FPGA (Quartus/ISE/Gowin)",
      "PLC Siemens S7-200"
    ],
    "pcb_design": [
      {
        "herramienta": "Proteus",
        "experiencia": "Diseño de PCBs de pequeña escala para proyectos personales y académicos"
      }
    ],
    "simulacion_y_diseno": [
      "Sistemas digitales",
      "Sistemas de control",
      "Circuitos analógicos",
      "Telecomunicaciones básicas",
      "Sistemas SCADA y HMI",
      "Automatización de Procesos Neumáticos",
      "Redes de Comunicación Industrial (Modbus TCP, RS-485)",
      "Gemelos Digitales (Digital Twins)",
      "Redes de Petri"
    ],
    "documentacion": [
      "LaTeX",
      "circuitikz",
      "Draw.io"
    ],
    "habilidades_blandas": [
      "Trabajo liderando equipos en entornos multidisciplinarios",
      "Trabajo bajo presión y cumplimiento de plazos ajustados",
      "Proactividad ante resolución inmediata de problemas",
      "Creatividad aplicada a desafíos técnicos"
    ],
    "nuestro_nivel_general": "Avanzado"
  },
  "proyectos": {
    "proyectos": [
      {
        "id": "reconocimiento_ascii",
        "nombre": "Reconocimiento de caracteres ASCII usando IA integrada a un sistema digital",
        "tipo": "Personal / Integración Hardware-Software",
        "herramientas": [
          "Python",
          "AHPL",
          "VHDL",
          "Proteus",
          "Arduino"
        ],
        "descripcion": "Diseño de un sistema entrenado para reconocer caracteres ASCII a partir de imágenes o señales.",
        "resultado": "El sistema fue funcional y cumplió su propósito correctamente."
      },
      {
        "id": "osciloscopio_crt",
        "nombre": "Osciloscopio utilizando un televisor CRT",
        "tipo": "Personal / Desarrollo Electrónico",
        "herramientas": [
          "Electrónica analógica",
          "Deflexión electrónica",
          "Control análogo"
        ],
        "descripcion": "Construcción de un osciloscopio básico reutilizando un televisor CRT antiguo.",
        "resultado": "Aplicación exitosa de conceptos de deflexión, sincronización y modulación analógica."
      },
      {
        "id": "vsrg_piano_8086",
        "nombre": "VSRG-Piano 8086",
        "tipo": "Personal / Programación de Bajo Nivel y Emulación",
        "herramientas": [
          "Ensamblador x86 (16 bits)",
          "MASM 5.0",
          "DOSBox",
          "PIT 8253",
          "Interrupciones de Hardware"
        ],
        "descripcion": "Juego de ritmo vertical de 12 teclas para MS-DOS/DOSBox. Implementa sonido polifónico TDM sobre el PC Speaker de un solo canal, un controlador de teclado personalizado por hardware (IRQ 1) para soportar múltiples teclas simultáneas, y renderizado fluido sin parpadeos mediante scrolling por BIOS.",
        "resultado": "El juego es completamente funcional en DOSBox con soporte polifónico acústico estable y lectura dinámica de partituras binarias .par."
      },
      {
        "id": "simulador_2do_orden_8086",
        "nombre": "2nd-Order Simulator 8086",
        "tipo": "Personal / Simulación Científica y Programación de Bajo Nivel",
        "herramientas": [
          "Ensamblador x86 (16 bits)",
          "FPU 8087/80387",
          "VGA Modo 12h (640x480)",
          "DOSBox",
          "Coprocesador Matemático"
        ],
        "descripcion": "Software interactivo para MS-DOS que simula y grafica en tiempo real la respuesta temporal (escalón, impulso y senoidal) de sistemas de control de segundo orden. Implementa aproximaciones discretas de ecuaciones diferenciales en punto flotante de doble precisión (64-bit) y calcula de forma automática métricas de rendimiento (tiempo de subida, sobrepico, tiempo de establecimiento, etc.) a través de interfaz gráfica con soporte para mouse.",
        "resultado": "Simulador totalmente funcional en DOSBox con trazado preciso de curvas de control y uso eficiente de la pila del coprocesador matemático (FPU)."
      },
      {
        "id": "simple_paint_8086",
        "nombre": "Simple Paint 8086",
        "tipo": "Personal / Gráficos por Computadora y Programación de Sistemas",
        "herramientas": [
          "Ensamblador x86 (16 bits)",
          "Bresenham Algorithm",
          "VGA Modo 12h (640x480)",
          "DOSBox",
          "Mouse Interrupts (Int 33h)"
        ],
        "descripcion": "Lienzo de dibujo libre para MS-DOS que implementa rasterización de líneas optimizada con solo enteros usando el Algoritmo de Línea de Bresenham en registros de 16 bits. Cuenta con un sistema para evitar conflictos de parpadeo del cursor del mouse ocultando y mostrando dinámicamente el puntero vía servicios de interrupción de mouse (Int 33h Fn 1 y 2), y ciclado automático de colores de paleta VGA en tiempo real.",
        "resultado": "Programa funcional y educativo en DOSBox que ilustra técnicas de optimización de vídeo y control de hardware de entrada en modo real."
      },
      {
        "id": "xk335b_digital_twin",
        "nombre": "Gemelo Digital y Control de la Estación Mecatrónica XK335B",
        "tipo": "Personal / Automatización, Procesos Neumáticos y Sistemas Ciberfísicos",
        "herramientas": [
          "Python (Flask)",
          "OpenPLC Runtime",
          "Structured Text (ST)",
          "Modbus TCP",
          "HTML/JS/CSS"
        ],
        "descripcion": "Desarrollo de un gemelo digital (simulador cinemático) para la estación de clasificación y ensamblaje mecatrónico XK335B, modelando el comportamiento físico de cintas transportadoras, servomotores y actuadores neumáticos. Implementa la lógica de control secuencial mediante una máquina de estados de 7 etapas programada en Structured Text (ST) sobre OpenPLC, y una interfaz HMI web en tiempo real para supervisión y control manual/automático mediante el protocolo Modbus TCP.",
        "resultado": "Simulación de procesos neumáticos y control secuencial en tiempo real completamente funcional, validando la integración de gemelos digitales en sistemas industriales."
      },
      {
        "id": "xk335b_scada",
        "nombre": "Sistema SCADA e Integración de la Planta Flexible XK-335B (S7-200)",
        "tipo": "Académico / Automatización Industrial, SCADA y Redes de Comunicación",
        "herramientas": [
          "PLC Siemens S7-200",
          "Step 7-Micro/WIN (Ladder/AWL)",
          "SCADA (Flask/Python/JS)",
          "RS-485 (Modbus)",
          "Redes de Petri"
        ],
        "descripcion": "Diseño y ejecución del sistema de automatización e integración de las 5 estaciones del proceso neumático de manufactura flexible de la planta XK-335B (Transporte, Prensa, Ensamblaje, Clasificación y Selección). Modelado lógico del proceso mediante Redes de Petri y traducción a lenguaje Ladder/AWL, configuración del intercambio de datos inter-PLC (NETR/NETW), y desarrollo de un SCADA multihilo con HMI web para el monitoreo de consignas, conteo de piezas y gestión centralizada de seguridad física (parada de emergencia) vía RS-485.",
        "resultado": "Control y monitoreo distribuido exitoso de la planta neumática flexible, garantizando el handshake entre estaciones y la supervisión web unificada."
      }
    ]
  },
  "educacion": {
    "universitaria": [
      {
        "titulo": "Ingeniería Electrónica",
        "institucion": "Universidad Mayor de San Andrés",
        "facultad": "Facultad de Ingeniería",
        "periodo": "2020 – 2026 (en curso)",
        "mencion": "Sistemas de Control",
        "reconocimientos": [
          "Reconocimiento al Mejor Estudiante de la gestión 2023 por parte del 'Curso Básico' de la Facultad de Ingeniería (otorgado a estudiantes destacados)"
        ],
        "actividades_institucionales": [
          {
            "rol": "Tribunal estudiantil",
            "descripcion": "Participación como tribunal estudiantil en cinco procesos de admisión de docentes y auxiliares de docencia, contando con 5 memorándums de respaldo institucional.",
            "documento_respaldo": "recursos/memorandums/respaldo_tribunal.pdf"
          },
          {
            "rol": "Auxiliar de Docencia",
            "descripcion": "Auxiliar de docencia de la asignatura Sistemas Digitales II (ETN821) para las gestiones I/2026 y II/2026."
          }
        ],
        "materias_destacadas": [
          "Inteligencia Artificial",
          "Sistemas de Control",
          "Sistemas Digitales"
        ]
      }
    ]
  },
  "experiencia": {
    "trabajos": [
      {
        "cargo": "Técnico en reparación de fuentes conmutadas",
        "tipo": "Trabajo independiente",
        "periodo": "2023",
        "descripcion": "Trabajo independiente relacionado con la carrera de ingeniería electrónica.",
        "logros": [
          "Reparación, análisis y mantenimiento de fuentes de alimentación conmutadas.",
          "Fortalecimiento de conocimientos prácticos en electrónica analógica práctica."
        ]
      },
      {
        "cargo": "Ayudante redes y cableado estructurado",
        "tipo": "Trabajo independiente/eventual",
        "periodo": "2025-2026",
        "descripcion": "Servicio de cableado estructurado para oficinas y entornos industriales",
        "logros": [
          "Experiancia con normas de seguridad en entornos industriales.",
          "Trabajo bajo presion."
        ]
      }
    ]
  },
  "certificaciones": {
    "certificados": [
      {
        "titulo": "Curso de ensamblaje de PC y laptops",
        "institucion": "Instituto INFOCAL",
        "periodo": "...",
        "archivo_respaldo": "recursos/certificados/certificado_infocal.pdf"
      },
      {
        "titulo": "Primer año de Sistemas Informáticos",
        "institucion": "Instituto INCOS",
        "periodo": "...",
        "estado": "estudios congelados",
        "archivo_respaldo": "recursos/certificados/certificado_incos.pdf"
      },
      {
        "titulo": "Técnico Medio en Aplicaciones",
        "institucion": "Instituto ITEC",
        "periodo": "...",
        "archivo_respaldo": "recursos/certificados/certificado_itec.jpg"
      }
    ]
  },
  "idiomas": {
    "idiomas": [
      {
        "idioma": "Español",
        "nivel": "Nativo"
      },
      {
        "idioma": "Inglés",
        "competencias": {
          "lectura": "Avanzado",
          "escritura": "Intermedio",
          "escucha": "Intermedio",
          "habla": "Intermedio"
        },
        "notas": [
          "Amplia experiencia manejando documentación técnica en inglés (libros, papers y hojas de datos).",
          "Fluidez y comodidad participando en entrevistas en inglés."
        ]
      },
      {
        "idioma": "Esperanto",
        "nivel": "Principiante",
        "notas": [
          "Por Hobby"
        ]
      }
    ]
  },
  "intereses": {
    "intereses": {
      "areas_de_interes": [
        "Inteligencia Artificial",
        "Sistemas Embebidos"
      ],
      "desarrollo_multidisciplinario": [
        "Medicina",
        "Informática",
        "Energías"
      ],
      "planes_academicos": [
        "Estudios de Postgrado",
        "Segunda carrera en Física"
      ],
      "entornos": [
        "Académico (Investigación)",
        "Industrial (Consultoría y desarrollo)"
      ],
      "tipo_industria": "Empresas tecnológicas y de consultoría desafiantes y competitivas",
      "expectativas": "Entorno de trabajo desafiante y competitivo que ponga a prueba mis capacidades y permita el crecimiento continuo"
    }
  }
};
