import os
import yaml
import json

def build():
    datos_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'datos'))
    portfolio_dir = os.path.dirname(os.path.abspath(__file__))
    js_dir = os.path.join(portfolio_dir, 'js')
    
    if not os.path.exists(js_dir):
        os.makedirs(js_dir)
        
    data = {}
    
    files = [
        'contacto.yaml',
        'habilidades.yaml',
        'proyectos.yaml',
        'educacion.yaml',
        'experiencia.yaml',
        'certificaciones.yaml',
        'idiomas.yaml',
        'intereses.yaml'
    ]
    
    for f in files:
        path = os.path.join(datos_dir, f)
        if os.path.exists(path):
            key = f.split('.')[0]
            with open(path, 'r', encoding='utf-8') as file_content:
                data[key] = yaml.safe_load(file_content)
        else:
            print(f"Warning: {f} not found in {datos_dir}")
            
    js_content = f"// Generated by build_data.py. Do not edit directly.\nconst PORTFOLIO_DATA = {json.dumps(data, indent=2, ensure_ascii=False)};\n"
    
    output_path = os.path.join(js_dir, 'data.js')
    with open(output_path, 'w', encoding='utf-8') as out:
        out.write(js_content)
    print(f"Successfully generated {output_path}")

if __name__ == '__main__':
    build()
